const nb = 8;
const questions = [
	[ '01-Ai_hanmi_katatedori_ikkyo_omote_waza.mp4', 'Ai hanmi katate dori <u>ikkyo omote</u> waza'],
	[ '02-Ai_hanmi_katatedori_ikkyo_ura_waza.mp4', 'Ai hanmi katate dori <u>ikkyo ura</u> waza'],
	[ '03-Ai_hanmi_katatedori_nikyo_omote_waza.mp4', 'Ai hanmi katate dori <u>nikyo omote</u> waza'],
	[ '04-Ai_hanmi_katatedori_nikyo_ura_waza.mp4', 'Ai hanmi katate dori <u>nikyo ura</u> waza'],
	[ '05-Ai_Hamni_Katate_Dori_Sankyo_omoto_waza.mp4', 'Ai hanmi katate dori <u>sankyo omote</u> waza'],
	[ '06-Ai_Hamni_Katate_Dori_sankyo_ura_waza.mp4', 'Ai hanmi katate dori <u>sankyo ura</u> waza'],
	[ '07-Ai_Hamni_Katate_Dori_Yonkyo_Omote_waza.mp4', 'Ai hanmi katate dori <u>yonkyo omote</u> waza'],
	[ '08-Ai_Hamni_Katate_Dori_yonkyo_ura_waza.mp4', 'Ai hanmi katate dori <u>yonkyo ura</u> waza'],
	[ '09-Ai_Hamni_Katate_Dori_Shiho_nage_omote.mp4', 'Ai hanmi katate dori <u>Shiho nage omote</u> waza'],
	[ '10-Ai_Hamni_Katate_Dori_Shiho_Nage_ura.mp4', 'Ai hanmi katate dori <u>Shiho nage ura</u> waza'],
	[ '11-Ai_Hamni_Katate_Dori_Irimi_Nage_v1.mp4', 'Ai hanmi katate dori <u>Irimi nage v1</u> waza'],
	[ '12-Ai_Hamni_Katate_Dori_Irimi_Nage_v2.mp4', 'Ai hanmi katate dori <u>Irimi nage v2</u> waza'],
	[ '13-Ai_Hamni_Katate_Dori_Irimi_Nage_v3.mp4', 'Ai hanmi katate dori <u>Irimi nage v3</u> waza'],
	[ '14-Ai_Hamni_Katate_Dori_KoteGaeshi_v1.mp4', 'Ai hanmi katate dori <u>Kote Gaeshi v1</u> waza'],
	[ '15-Ai_Hamni_Katate_Dori_KoteGaeshi_v2.mp4', 'Ai hanmi katate dori <u>Kote Gaeshi v2</u> waza'],
	[ '17-Ai_Hamni_Katate_Dori_Koshi_Nage.mp4', 'Ai hanmi katate dori <u>Irimi nage v2</u> waza'],
	[ '18-Ai_Hamni_Katate_Dori_-_Ushiro_nage.mp4', 'Ai hanmi katate dori <u>Ushiro nage</u> waza'],
	[ '19-Ai_Hamni_Katate_Dori_Ude_gatan.mp4', 'Ai hanmi katate dori <u>Ude Gatan</u> waza'],
	[ '20-Ai hanmi katatedori-20.mp4', 'Ai hanmi katate dori Kenka waza'],
	[ '21-Ai hanmi katatedori-21.mp4', 'Ai hanmi katate dori Kenka waza v2'],
	['01-Ryote_Dori_ikkyo_omote_waza.mp4', 'Ryote Dori <u>ikkyo omote</u> waza'],
	['02-Ryote_Dori_ikkyo_ura_waza.mp4', 'Ryote Dori <u>ikkyo ura</u> waza'],
	['03-Ryote_Dori_Nikyo_omote_waza.mp4', 'Ryote Dori <u>Nikyo omote</u> waza'],
	['04-Ryote_Dori_Nikyo_ura_waza.mp4', 'Ryote Dori <u>Nikyo ura</u> waza'],
	['05-Ryote_Dori_Sankyo_omote_waza.mp4', 'Ryote Dori <u>Sankyo omote</u> waza'],
	['06-Ryote_Dori_Sankyo_ura_waza.mp4', 'Ryote Dori <u>Sankyo ura</u> waza'],
	['07-Ryote_Dori_yonkyo_omote_waza.mp4', 'Ryote Dori <u>yonkyo omote</u> waza'],
	['08-Ryote_Dori_yonkyo_ura_waza.mp4', 'Ryote Dori <u>yonkyo ura</u> waza'],
	['09-Ryote_Dori_Gokyo_omote_waza.mp4', 'Ryote Dori <u>Gokyo omote</u> waza'],
	['10-Ryote_Dori_Gokyo_ura_waza.mp4', 'Ryote Dori <u>Gokyo ura</u> waza'],
	['11-Ryote_Dori_Shiho_nage_omote_waza.mp4', 'Ryote Dori <u>Shiho nage omote</u> waza'],
	['12-Ryote_Dori_Shiho_nage_ura_waza.mp4', 'Ryote Dori <u>Shiho nage ura</u> waza'],
	['13-Ryote_Dori_Shiho_nage_v3.mp4', 'Ryote Dori <u>Shiho nage</u> v3'],
	['14-Ryote_Dori_Irimi_nage_jodan.mp4', 'Ryote Dori <u>Irimi nage</u> jodan'],
	['15-Ryote_Dori_Irimi_nage_shiho_nage_jodan.mp4', 'Ryote Dori <u>Irimi nage shiho nage</u> jodan'],
	['16-Ryote_Dori_Irimi_nage_Gedan.mp4', 'Ryote Dori <u>Irimi nage</u> Gedan'],
	['17-Ryote_Dori_Shiho_nage_irimi_nage_gedan.mp4', 'Ryote Dori <u>Shiho nage irimi nage</u> gedan'],
	['18-Ryote_Dori_Irimi_nage_chudan.mp4', 'Ryote Dori <u>Irimi nage</u> chudan'],
	['19-Ryote_Dori_Kino_nage_irimi_nage_shodan.mp4', 'Ryote Dori <u>Kino nage irimi nag</u>e shodan'],
	['20-Ryote_Dori_Kote_Gaeshi_v1.mp4', 'Ryote Dori <u>Kote Gaeshi</u> v1'],
	['21-Ryote_Dori_Kote_Gaeshi_v2.mp4', 'Ryote Dori <u>Kote Gaeshi</u> v2'],
	['22-Ryote_Dori_Kaiten_nage.mp4', 'Ryote Dori <u>Kaiten nage</u>'],
	['23-Ryote_Dori_Koshi_nage_v1.mp4', 'Ryote Dori <u>Koshi nage</u> v1'],
	['24-Ryote_Dori_Koshi_nage_v2.mp4', 'Ryote Dori <u>Koshi nage</u> v2'],
	['25-Ryote_Dori_Koshi_nage_v3.mp4', 'Ryote Dori <u>Koshi nage</u> v3'],
	['26-Ryote_Dori_Tenchi_nage.mp4', 'Ryote Dori <u>Tenchi nage</u>'],
	['27-Ryote_Dori_Shiho___tenchi_nage.mp4', 'Ryote Dori <u>Shiho _ tenchi nage</u>'],
	['28-Ryote_Dori_Kokyu_nage_v1.mp4', 'Ryote Dori <u>Kokyu nage</u> v1'],
	['29-Ryote_Dori_Kokyu_nage_v2.mp4', 'Ryote Dori <u>Kokyu nage</u> v2'],
	['30-Ryote_Dori_Kokyu_nage_v3.mp4', 'Ryote Dori <u>Kokyu nage</u> v3'],
	['31-Ryote_Dori_Ikkyo_waza.mp4', 'Ryote Dori <u>Ikkyo</u> waza'],
	['32-Ryote_Dori_Nikyo_waza.mp4', 'Ryote Dori <u>Nikyo</u> waza'],
	['Ryote_dori-33.mp4', 'Ryote dori 33'],
	['Ryote_dori-34.mp4', ' Ryote dori 34'],
	['Ryote_dori-35.mp4', 'Ryote dori 35'],
	['Ryote_dori-36.mp4', 'Ryote dori 36'],
	['01-Katate_dori_ikkyo_omote_waza.mp4', 'Katate dori <u>ikkyo omote</u> waza'],
	['02-Katate_dori_ikkyo_ura_waza.mp4', 'Katate dori <u>ikkyo ura</u> waza'],
	['03-Katate_Dori_Nikyo_omote_waza_.mp4', 'Katate Dori <u>Nikyo omote</u> waza '],
	['04-Katate_Dori_Nikyo_ura_waza.mp4', 'Katate Dori <u>Nikyo ura</u> waza'],
	['05-Katate_Dori_Sankyo_omote_waza_.mp4', 'Katate Dori <u>Sankyo omote</u> waza '],
	['06-Katate_Dori_Sankyo_ura_waza.mp4', 'Katate Dori <u>Sankyo ura</u> waza'],
	['07-Katate_Dori_Yonkyo_omote_waza.mp4', 'Katate Dori <u>Yonkyo omote</u> waza'],
	['08-Katate_Dori_Yonkyo_ura_waza.mp4', 'Katate Dori <u>Yonkyo ura</u> waza'],
	['09-Katate_Dori__Gokyo_omote_waza.mp4', 'Katate Dori <u>Gokyo omote</u> waza'],
	['10-Katate_Dori_Gokyo_ura_waza.mp4', 'Katate Dori <u>Gokyo ura</u> waza'],
	['11-Katate_Dori_Shiho_nage_omote_waza.mp4', 'Katate Dori <u>Shiho nage omote</u> waza'],
	['12-Katate_Dori_Shiho_nage_ura_waza.mp4', 'Katate Dori <u>Shiho nage ura</u> waza'],
	['13-Katate_Dori_Shiho_nage_kenka_waza.mp4', 'Katate Dori <u>Shiho nage</u> kenka waza'],
	['14-Katate_Dori_Shiho_nage_omote_waza_v2.mp4', 'Katate Dori <u>Shiho nage omote</u> waza v2'],
	['15-Katate_Dori_Shiho_nage_ura_waza_v2.mp4', 'Katate Dori <u>Shiho nage ura</u> waza v2'],
	['16-Katate_Dori_Irimi_nage_jodan.mp4', 'Katate Dori <u>Irimi nage</u> jodan'],
	['17-Katate_Dori_irimi_nage_jodan_v2.mp4', 'Katate Dori <u>irimi nage</u> jodan v2'],
	['18-Katate_Dori__Irimi_nage_gedan.mp4', 'Katate Dori  <u>Irimi nage</u> gedan'],
	['19-Katate_Dori_-__Irimi_nage_ushiro_nage_gedan.mp4', 'Katate Dori <u>Irimi nage ushiro nage</u> gedan'],
	['20-Katate_Dori_Irimi_nage_chudan.mp4', 'Katate Dori <u>Irimi nage</u> chudan'],
	['21-Katate_Dori_____irimi_nage_chudan.mp4', 'Katate Dori ___ <u>irimi nage</u> chudan'],
	['22-Katate_Dori_Koshinage.mp4', 'Katate Dori <u>Koshi nage</u>'],
	['23-Katate_Dori_koshi_nage_v2.mp4', 'Katate Dori <u>koshi nage</u> v2'],
	['24-Katate_Dori__Kokyu_nage.mp4', 'Katate Dori <u>Kokyu nage</u>'],
	['25-Katate_Dori_Kokyu_nage_v2.mp4', 'Katate Dori <u>Kokyu nage</u> v2'],
	['26-Katate_Dori_Kokyu_nage_v3.mp4', 'Katate Dori <u>Kokyu nage</u> v3'],
	['27-Katate_Dori_Kokyu_nage_v4.mp4', 'Katate Dori <u>Kokyu nage</u> v4'],
	['28-Katate_Dori_Balayage_(sans_nom).mp4', 'Katate Dori Balayage (sans nom)'],
	['29-Katate_Dori_-balayage.mp4', 'Katate Dori balayage'],
	['30-Katate_Dori_____kokyu_nage.mp4', 'Katate Dori ___ <u>kokyu nage</u>'],
	['31-Katate_Dori_-_Kokyu_nage_v5.mp4', 'Katate Dori <u>Kokyu nage</u> v5'],
	['32-Katate_Dori_Kokyu_nage_v6.mp4', 'Katate Dori <u>Kokyu nage</u> v6'],
	['33-Katate_Dori_Kokyu_nage_v7.mp4', 'Katate Dori <u>Kokyu nage</u> v7'],
	['34-Katate_Dori_(sans_nom_v2).mp4', 'Katate Dori (sans nom v2)'],
	['35-Katate_Dori_-_____waza.mp4', ' Katate Dori___ waza'],
	['36-Katate_Dori____.mp4', 'Katate Dori ___'],
	['37-Katate_Dori__(coude).mp4', 'Katate Dori _(coude)'],
	['38-Katate_Dori_(sans_nom_v3).mp4', 'Katate Dori (sans nom v3)'],
	['39-Katate_Dori_Nikyo_oyo_waza.mp4', 'Katate Dori <u>Nikyo oyo</u> waza'],
	['40-Katate_Dori_(sans_nom_v4).mp4', 'Katate Dori (sans nom v4)'],
	['01-Shomen_Uchi_Ikkyo_omote_waza.mp4', 'Shomen Uchi <u>Ikkyo omote</u> waza'],
	['02-Shomen_Uchi_Ikkyo_ura_waza.mp4', 'Shomen Uchi <u>Ikkyo ura</u> waza'],
	['03-Shomen_Uchi_Nikyo_omote_waza.mp4', 'Shomen Uchi <u>Nikyo omote</u> waza'],
	['04-Shomen_Uchi_Nikyo_ura_waza.mp4', 'Shomen Uchi <u>Nikyo ura</u> waza'],
	['05-Shomen_Uchi_Sankyo_omote_waza_v1.mp4', 'Shomen Uchi <u>Sankyo omote</u> waza v1'],
	['06-Shomen_Uchi_Sankyo_omote_waza_v2.mp4', 'Shomen Uchi <u>Sankyo omote</u> waza v2'],
	['07-Shomen_Uchi_Sankyo_ura_waza.mp4', 'Shomen Uchi Sankyo ura waza'],
	['08-Shomen_Uchi_Sankyo_ura_waza_v2.mp4', 'Shomen Uchi <u>Sankyo ura</u> waza v2'],
	['09-Shomen_Uchi__sankyo_kenka_waza_v1.mp4', 'Shomen Uchi  <u>sankyo</u> kenka waza v1'],
	['10-Shomen_Uchi_sankyo_kenka_waza_v2.mp4', 'Shomen Uchi <u>sankyo</u> kenka waza v2'],
	['11-Shomen_Uchi_Sankyo_kenka_waza_v3.mp4', 'Shomen Uchi <u>Sankyo</u> kenka waza v3'],
	['12-Shomen_Uchi_Sankyo_kenka_waza_v4.mp4', 'Shomen Uchi <u>Sankyo</u> kenka waza v4'],
	['13-Shomen_Uchi_Sankyo_kenka_waza_v5.mp4', 'Shomen Uchi <u>Sankyo</u> kenka waza v5'],
	['14-Shomen_Uchi_Yonkyo_omote_waza.mp4', 'Shomen Uchi <u>Yonkyo omote</u> waza'],
	['15-Shomen_Uchi_Yonkyo_ura_waza.mp4', 'Shomen Uchi <u>Yonkyo ura</u> waza'],
	['16-Shomen_Uchi_Gokyo_omote_waza.mp4', 'Shomen Uchi <u>Gokyo omote</u> waza'],
	['17-Shomen_Uchi_Gokyo_ura.mp4', 'Shomen Uchi <u>Gokyo ura</u>'],
	['18-Shomen_Uchi_Shiho_nage_v1.mp4', 'Shomen Uchi <u>Shiho nage</u> v1'],
	['19-Shomen_Uchi_Shiho_nage_v2.mp4', 'Shomen Uchi <u>Shiho nage</u> v2'],
	['20-Shomen_Uchi_Irimi_nage_v1.mp4', 'Shomen Uchi <u>Irimi nage</u> v1'],
	['21-Shomen_Uchi_Irimi_nage_v2.mp4', 'Shomen Uchi <u>Irimi nage</u> v2'],
	['22-Shomen_Uchi_Shiho_nage_irimi_nage.mp4', 'Shomen Uchi <u>Shiho nage irimi nage</u>'],
	['23-Shomen_Uchi_Iriminage_kenka.mp4', 'Shomen Uchi <u>Irimi nage</u> kenka'],
	['24-Shomen_Uchi_-_katatedori_iriminage.mp4', 'Shomen Uchi katatedori <u>irimi nage</u>'],
	['25-Shomen_Uchi_kenka_katate_dori_no_nage.mp4', 'Shomen Uchi kenka katate dori no nage'],
	['26-Shomen_Uchi_Irimi_nage_kenka_v2.mp4', 'Shomen Uchi <u>Irimi nage</u> kenka v2'],
	['27-Shomen_Uchi_Kote_Gaeshi.mp4', 'Shomen Uchi <u>Kote Gaeshi</u>'],
	['28-Shomen_Uchi_Kote_Gaeshi_v2.mp4', 'Shomen Uchi <u>Kote Gaeshi</u> v2'],
	['29-Shomen_Uchi_Kote_Gaeshi_mindo_waza.mp4', 'Shomen Uchi <u>Kote Gaeshi</u> mindo waza'],
	['30-Shomen_Uchi_Kaiten_nage.mp4', 'Shomen Uchi <u>Kaiten nage</u>'],
	['31-Shomen_Uchi_Kaiten_nage_v2.mp4', 'Shomen Uchi Kaiten nage v2'],
	['32-Shomen_Uchi_-_Kaiten_nage_v3.mp4', 'Shomen Uchi <u>Kaiten nage</u> v3'],
	['33-Shomen_Uchi_Koshinage.mp4', 'Shomen Uchi <u>Koshi nage</u>'],
	['34-Shomen_Uchi_-_koshinage_v2.mp4', 'Shomen Uchi <u>Koshi nage</u> v2'],
	['35-Shomen_Uchi_Juji_nage.mp4', 'Shomen Uchi <u>Juji nage</u>'],
	['36-Shomen_Uchi_Kokyu_nage.mp4', 'Shomen Uchi <u>Kokyu nage</u>'],
	['37-Shomen_Uchi_Kokyuho_nage.mp4', 'Shomen Uchi <u>Kokyu nage</u>'],
	['38-Shomen_Uchi_Goseki_Otoshi.mp4', 'Shomen Uchi <u>Goseki Otoshi</u>'],
	['39-Shomen_Uchi_Kokyu_nage_v2.mp4', 'Shomen Uchi <u>Kokyu nage</u> v2'],
	['40-Shomen_Uchi_Kokyu_nage_v3.mp4', 'Shomen Uchi <u>Kokyu nage</u> v3'],
	['41-Shomen_Uchi_kenka_waza.mp4', 'Shomen Uchi kenka waza'],
	['42-Shomen_Uchi_Kenka_waza_v2.mp4', 'Shomen Uchi Kenka waza v2'],
	['01-Tsuki_Ikkyo.mp4', 'Tsuki Ikkyo'],
	['02-Tsuki_Nikyo.mp4', 'Tsuki Nikyo'],
	['03-Tsuki_Shiho_nage.mp4', 'Tsuki Shiho nage'],
	['04-Tsuki__Kote_gaeshi.mp4', 'Tsuki  Kote gaeshi'],
	['05-Tsuki_Irimi_nage.mp4', 'Tsuki Irimi nage'],
	['06-Tsuki_Sankyo.mp4', 'Tsuki Sankyo'],
	['07-Tsuki_____v1.mp4', 'Tsuki ___ v1'],
	['08-Tsuki_____v2.mp4', 'Tsuki ___ v2'],
	['09-Tsuki_____v3.mp4', 'Tsuki ___ v3'],
	['01-Ni_Nin_Dori_Kokyu_nage.mp4', 'Ni Nin Dori <u>Kokyu nage</u>'],
	['02-Ni_Nin_Dori_Kokyu_nage_v2.mp4', 'Ni Nin Dori <u>Kokyu nage</u> v2'],
	['03-Ni_Nin_Dori__Kokyu_nage_v3.mp4', 'Ni Nin Dori <u>Kokyu nage</u> v3'],
	['04-Ni_Nin_Dori_Ikkyo_waza.mp4', 'Ni Nin Dori <u>Ikkyo</u> waza'],
	['05-Ni_Nin_Dori_Kokyu_nage_irimi_nage.mp4', 'Ni Nin Dori <u>Kokyu nage irimi nage</u>'],
	['06-Ni_Nin_Dori_Kokyu_nage_v4.mp4', 'Ni Nin Dori <u>Kokyu nage</u> v4'],
	['01-Ushiro_Ryote_Dori_Ikkyo_omote_waza.mp4', 'Ushiro Ryote Dori <u>Ikkyo omote</u> waza'],
	['02-Ushiro_Ryote_Dori_Ikkyo_ura_waza.mp4', 'Ushiro Ryote Dori <u>Ikkyo ura</u> waza'],
	['03-Ushiro_Ryote_Dori_Ikkyo_omote.mp4', 'Ushiro Ryote Dori <u>Ikkyo omote</u>'],
	['04-Ushiro_Ryote_Dori_Ikkyo_ura.mp4', 'Ushiro Ryote Dori <u>Ikkyo ura</u>'],
	['05-Ushiro_Ryote_Dori_Nikyo_omote_waza.mp4', 'Ushiro Ryote Dori <u>Nikyo omote</u> waza'],
	['06-Ushiro_Ryote_Dori_Nikyo_Ura_waza.mp4', 'Ushiro Ryote Dori <u>Nikyo Ura</u> waza'],
	['07-Ushiro_Ryote_Dori_Sankyo_omote_waza_.mp4', 'Ushiro Ryote Dori <u>Sankyo omote</u> waza '],
	['08-Ushiro_Ryote_Dori_Sankyo_ura_waza.mp4', 'Ushiro Ryote Dori <u>Sankyo ura</u> waza'],
	['09-Ushiro_Ryote_Dori_Yonkyo_omote_waza.mp4', 'Ushiro Ryote Dori <u>Yonkyo omote</u> waza'],
	['10-Ushiro_Ryote_Dori__Yonkyo_ura_waza.mp4', 'Ushiro Ryote Dori  <u>Yonkyo ura</u> waza'],
	['11-Ushiro_Ryote_Dori_Sankyo_Kenka_waza.mp4', 'Ushiro Ryote Dori <u>Sankyo</u> Kenka waza'],
	['12-Ushiro_Ryote_Dori_Sankyo_v2.mp4', 'Ushiro Ryote Dori <u>Sankyo</u> v2'],
	['13-Ushiro_Ryote_Dori_Irimi_nage.mp4', 'Ushiro Ryote Dori <u>Irimi nage</u>'],
	['14-Ushiro_Ryote_Dori_Kote_Gaeshi.mp4', 'Ushiro Ryote Dori <u>Kote Gaeshi</u>'],
	['15-Ushiro_Ryote_Dori_Kote_Gaeshi_v2.mp4', 'Ushiro Ryote Dori <u>Kote Gaeshi</u> v2'],
	['16-Ushiro_Ryote_Dori_Koshinage.mp4', 'Ushiro Ryote Dori <u>Koshi nage</u>'],
	['17-Ushiro_Ryote_Dori_Kshinage_v2.mp4', 'Ushiro Ryote Dori <u>Koshi nage</u> v2'],
	['18-Ushiro_Ryote_Dori_Koshinage_v3.mp4', 'Ushiro Ryote Dori <u>Koshi nage</u> v3'],
	['19-Ushiro_Ryote_Dori_Juji_nage.mp4', 'Ushiro Ryote Dori <u>Juji nage</u>'],
	['20-Ushiro_Ryote_Dori_Kokyu_ho.mp4', 'Ushiro Ryote Dori <u>Kokyu</u> ho'],
	['21-Ushiro_Ryote_Dori_(sans_nom).mp4', 'Ushiro Ryote Dori (sans nom)'],
	['22-Ushiro_Ryote_Dori_Ai_Hanmi.mp4', 'Ushiro Ryote Dori Ai Hanmi'],
	['23-Ushiro_Ryote_Dori_Kokyu_nage.mp4', 'Ushiro Ryote Dori <u>Kokyu nage</u>'],
	['24-Ushiro_Ryote_Dori_Kokyu_nage_v2.mp4', 'Ushiro Ryote Dori <u>Kokyu nage</u> v2'],
	['25-Ushiro_Ryote_Dori_Kenka_waza.mp4', 'Ushiro Ryote Dori Kenka waza'],
	['12_jo_dori-01.mp4', '12 jo dori 01 voir profs'],
	['12_jo_dori-02.mp4', '12 jo dori 02 voir profs'],
	['12_jo_dori-03.mp4', '12 jo dori 03 voir profs'],
	['12_jo_dori-04.mp4', '12 jo dori 04 voir profs'],
	['12_jo_dori-05.mp4', '12 jo dori 05 voir profs'],
	['12_jo_dori-06.mp4', '12 jo dori 06 voir profs'],
	['12_jo_dori-07.mp4', '12 jo dori 07 voir profs'],
	['12_jo_dori-08.mp4', '12 jo dori 08 voir profs'],
	['12_jo_dori-09.mp4', '12 jo dori 09 voir profs'],
	['12_jo_dori-10.mp4', '12 jo dori 10 voir profs'],
	['12_jo_dori-11.mp4', '12 jo dori 11 voir profs'],
	['12_jo_dori-12.mp4', '12 jo dori 12 voir profs'],
	['01-UW_Ushiro_Mune_katatedori_Kokyu_nage.mp4', 'Ushiro Mune katatedori <u>Kokyu nage</u>'],
	['02-UW_Ushiro_Mune_katatedori_Ko_no_nagare_kokyu_nage.mp4', 'Ushiro Mune katatedori Ko no nagare <u>kokyu nage</u>'],
	['03-UW_Ushiro_Mune_katatedori_koshinage.mp4', 'Ushiro Mune katatedori <u>koshi nage</u>'],
	['04-UW_Ushiro_Mune_katatedori_koshinage_v2.mp4', 'Ushiro Mune katatedori <u>koshi nage</u> v2'],
	['05-UW_Ki_no_nagare_Ushiro_Mune_katatedori_koshinage_v3.mp4', 'Ki no nagare Ushiro Mune katatedori <u>kosh inage</u> v3'],
	['06-UW_Ushiro_Mune_katatedori_Juji_nage.mp4', 'Ushiro Mune katatedori <u>Juji nage</u>'],
	['07-UW_Ushiro_Mune_katatedori_Juji_nage_v2.mp4', 'Ushiro Mune katatedori <u>Juji nage</u> v2'],
	['08-UW_Ushiro_Waza_katatedori_Juji_nage_v3.mp4', 'Ushiro Waza katatedori <u>Juji nage</u> v3'],
	['09-UW_Ushiro_Mune_katate_dori_Kenka_waza.mp4', 'Ushiro Mune katate dori Kenka waza'],
	['10-UW_Ushiro_Mune_katate_dori_Kenka_waza_v2.mp4', 'Ushiro Mune katate dori Kenka waza v2'],
	['11-UW_Ushiro_Eri_Dori_Ikkyo_omote.mp4', 'Ushiro Eri Dori <u>Ikkyo omote</u>'],
	['12-UW_Ushiro_Eri_Dori_Ikkyo_ura_waza.mp4', 'Ushiro Eri Dori <u>Ikkyo ura</u> waza'],
	['13-UW_Ushiro_Eri_Dori_Nikyo.mp4', 'Ushiro Eri Dori <u>Nikyo</u>'],
	['14-UW_Ushiro_Eri_Dori_Sankyo.mp4', 'Ushiro Eri Dori <u>Sankyo</u>'],
	['15-UW_Ushiro_Eri_Dori_Yonkyo.mp4', 'Ushiro Eri Dori <u>Yonkyo</u>'],
	['16-UW_Ushiro_Eri_Dori_Irimi_nage.mp4', 'Ushiro Eri Dori <u>Irimi nage</u>'],
	['17-UW_Ushiro_Eri_Dori_Kokyu_nage.mp4', 'Ushiro Eri Dori <u>Kokyu nage</u>'],
	['18-UW_Ushiro_Eri_Dori_Shiho_nage.mp4', 'Ushiro Eri Dori <u>Shiho nage</u>'],
	['19-UW_Ushiro_Eri_Dori_Kote_Gaeshi.mp4', 'Ushiro Eri Dori <u>Kote Gaeshi</u>'],
	['20-UW_Ushiro_Eri_Dori_Koshi_nage.mp4', 'Ushiro Eri Dori <u>Koshi nage</u>'],
	['21-UW_Ushiro_Eri_Dori_Irimi_nage_v2.mp4', 'Ushiro Eri Dori <u>Irimi nage</u> v2'],
	['22-UW_Ushiro_Eri_Dori_Kokyu_Nage_v2.mp4', 'Ushiro Eri Dori <u>Kokyu Nage</u> v2'],
	['23-UW_Ushiro_Eri_Dori_Kenka_waza.mp4', 'Ushiro Eri Dori Kenka waza'],
	['24-UW_Ushiro_Eri_Katate_dori_Irimi_nage.mp4', 'Ushiro Eri Katate dori <u>Irimi nage</u>'],
	['25-UW_Ushiro_Ryo_kata_dori_Ikkyo_omote_waza.mp4', 'Ushiro Ryo kata dori <u>Ikkyo omote</u> waza'],
	['26-UW_Ushiro_Ryo_kata_dori_Ikkyo_ura_waza.mp4', 'Ushiro Ryo kata dori <u>Ikkyo ura</u> waza'],
	['27-UW_Ushiro_Ryo_kata_dori_Nikyo.mp4', 'Ushiro Ryo kata dori <u>Nikyo</u>'],
	['28-UW_Ushiro_Ryo_kata_dori__Sankyo.mp4', 'Ushiro Ryo kata dori  <u>Sankyo</u>'],
	['29-UW_Ushiro_Ryo_kata_dori_Yonkyo.mp4', 'Ushiro Ryo kata dori <u>Yonkyo</u>'],
	['30-UW_Ushiro_Ryo_kata_dori_Kokyu_Nage.mp4', 'Ushiro Ryo kata dori <u>Kokyu Nage</u>'],
	['31-UW_Ushiro_Ryo_kata_dori_Kokyu_Nage_v2.mp4', 'Ushiro Ryo kata dori <u>Kokyu Nage</u> v2'],
	['32-UW_Ushiro_Ryo_kata_dori_Juji_nage.mp4', 'Ushiro Ryo kata dori <u>Juji nage</u>'],
	['33-UW_Ushiro_Ryo_kata_dori_Kote_Gaeshi.mp4', 'Ushiro Ryo kata dori <u>Kote Gaeshi</u>'],
	['34-UW_Ushiro_Ryo_kata_dori_Kenka_waza.mp4', 'Ushiro Ryo kata dori Kenka waza'],
	['35-UW_Ushiro_Ryo_kata_dori_Kenka_waza_v2.mp4', 'Ushiro Ryo kata dori Kenka waza v2'],
	['36-UW_Ushiro_Ryo_kata_dori_kenka_aiki_otoshi.mp4', 'Ushiro Ryo kata dori kenka <u>aiki otoshi</u>'],
	['37-UW_Ushiro_Ryo_kata_dori____.mp4', 'Ushiro Ryo kata dori ___'],
	['38-UW_Ushiro_Ryo_kata_dori_____v2.mp4', 'Ushiro Ryo kata dori ___ v2'],
	['39-UW_Ushiro_Ryo_kata_dori______v3.mp4', 'Ushiro Ryo kata dori  ___ v3'],
	['40-UW_Ushiro_Ryo_kata_dori_Osae____.mp4', 'Ushiro Ryo kata dori Osae ___'],
	['41-UW_Ushiro_Dori_Kokyu_Nage.mp4', 'Ushiro Dori <u>Kokyu Nage</u>'],
	['42-UW_Ushiro_Dori_Sankyo.mp4', 'Ushiro Dori <u>Sankyo</u>'],
	['43-UW_Ushiro_Dori_Kenka_waza.mp4', 'Ushiro Dori Kenka waza'],
	['44-UW_Ushiro_Dori_Kenka_waza_v2.mp4', 'Ushiro Dori Kenka waza v2'],
	['01-Morote_Dori_Kokyu_Ho_ich.mp4', 'Morote Dori <u>Kokyu Ho ich</u>'],
	['02-Morote_Dori_Kokyu_Ho_Ki_no_nagare.mp4', 'Morote Dori <u>Kokyu Ho</u> Ki no nagare'],
	['03-Morote_Dori_Kokyu_Ho_Ni.mp4', 'Morote Dori <u>Kokyu Ho Ni</u>'],
	['04-Morote_Dori_Kokyu_Ho_San.mp4', 'Morote Dori <u>Kokyu Ho San</u>'],
	['05-Morote_Dori_Kokyu_Ho_Yon.mp4', 'Morote Dori <u>Kokyu Ho Yon</u>'],
	['06-Morote_Dori_Kokyu_Ho_Go.mp4', 'Morote Dori <u>Kokyu Ho Go</u>'],
	['07-Morote_Dori_Ikkyo_omote_waza.mp4', 'Morote Dori <u>Ikkyo omote</u> waza'],
	['08-Morote_Dori_Ikkyo_ura_waza.mp4', 'Morote Dori <u>Ikkyo ura</u> waza'],
	['09-Morote_Dori_Ki_no_nagare_Ikkyo_omote_waza.mp4', 'Morote Dori Ki no nagare <u>Ikkyo omote</u> waza'],
	['10-Morote_Dori_Ki_no_nagare_Ikkyo_ura_waza.mp4', 'Morote Dori Ki no nagare <u>Ikkyo ura</u> waza'],
	['11-Morote_Dori_Nikyo.mp4', 'Morote Dori <u>Nikyo</u>'],
	['12-Morote_Dori_Ki_no_nagare_Nikyo.mp4', 'Morote Dori Ki no nagare <u>Nikyo</u>'],
	['13-Morote_Dori_Sankyo.mp4', 'Morote Dori <u>Sankyo</u>'],
	['14-Morote_Dori_Ki_no_nagare_Sankyo.mp4', 'Morote Dori Ki no nagare <u>Sankyo</u>'],
	['15-Morote_Dori_Yonkyo.mp4', 'Morote Dori <u>Yonkyo</u>'],
	['16-Morote_Dori_Ki_no_nagare_Yonkyo.mp4', 'Morote Dori Ki no nagare <u>Yonkyo</u>'],
	['17-Morote_Dori_Ki_no_nagare_Shiho_nage.mp4', 'Morote Dori Ki no nagare <u>Shiho nage</u>'],
	['18-Morote_Dori_Ki_no_nagare_Shiho_nage_v2.mp4', 'Morote Dori Ki no nagare <u>Shiho nage</u> v2'],
	['19-Morote_Dori_Irimi_nage.mp4', 'Morote Dori <u>Irimi nage</u>'],
	['20-Morote_Dori_Irimi_nage_v2.mp4', 'Morote Dori <u>Irimi nage</u> v2'],
	['21-_Morote_Dori_Ki_no_nagare_Irimi_nage.mp4', ' Morote Dori Ki no nagare <u>Irimi nage</u>'],
	['22-Morote_Dori_Ki_no_nagare_Irimi_nage_v2.mp4', 'Morote Dori Ki no nagare <u>Irimi nage</u> v2'],
	['23-Morote_Dori_Kote_Gaeshi.mp4', 'Morote Dori <u>Kote Gaeshi</u>'],
	['24-Morote_Dori_Ki_no_nagare_Kote_Gaeshi.mp4', 'Morote Dori Ki no nagare <u>Kote Gaeshi</u>'],
	['25-Morote_Dori_Koshi_nage_ich.mp4', 'Morote Dori <u>Koshi nage</u> ich'],
	['26-Morote_Dori_Koshi_nage_Ni.mp4', 'Morote Dori <u>Koshi nage</u> Ni'],
	['27-Morote_Dori_Koshi_nage_san.mp4', 'Morote Dori <u>Koshi nage</u> san'],
	['28-Morote_Dori_Koshi_nage_yon.mp4', 'Morote Dori <u>Koshi nage</u> yon'],
	['29-Morote_Dori_Koshi_nage_go.mp4', 'Morote Dori <u>Koshi nage</u> go'],
	['30-Morote_Dori_Ki_no_nagare_Koshi_nage_ich.mp4', 'Morote Dori Ki no nagare <u>Koshi nage</u> ich'],
	['31-Morote_Dori_Koshi_nage_ki_no_nagare_ni.mp4', 'Morote Dori <u>Koshi nage</u> ki no nagare ni'],
	['32-Morote_Dori_Koshi_nage_ki_no_nagare_san.mp4', 'Morote Dori <u>Koshi nage</u> ki no nagare san'],
	['33-Morote_Dori_Koshi_nage_ki_no_nagare_san_v2.mp4', 'Morote Dori <u>Koshi nage</u> ki no nagare san v2'],
	['34-Morote_Dori_Koshi_nage_ki_no_nagare_yon.mp4', 'Morote Dori <u>Koshi nage</u> ki no nagare yon'],
	['35-Morote_Dori_Koshi_nage_ki_no_nagare_go.mp4', 'Morote Dori <u>Koshi nage</u> ki no nagare go'],
	['36-Morote_Dori_Kokyu_nage.mp4', 'Morote Dori <u>Kokyu nage</u>'],
	['37-Morote_Dori_Kokyu_nage_(ki_no_nagare).mp4', 'Morote Dori <u>Kokyu nage</u> ki no nagare'],
	['38-Morote_Dori_Kokyu_nage_v2.mp4', 'Morote Dori <u>Kokyu nage</u> v2'],
	['39-Morote_Dori_Kokyu_nage_(ki_no_nagare)_v2.mp4', 'Morote Dori <u>Kokyu nage</u> ki no nagare v2'],
	['40-Morote_Dori_Kenka_waza.mp4', 'Morote Dori Kenka waza'],
	['41-Morote_Dori_Ki_no_nagare_kenka_waza.mp4', 'Morote Dori Ki no nagare kenka waza'],
	['01-Sode_Dori_Ikkyo_omote_waza.mp4', 'Sode Dori <u>Ikkyo omote</u> waza'],
	['02-Sode_Dori_Ikkyo_ura_waza.mp4', 'Sode Dori <u>Ikkyo ura</u> waza'],
	['03-Sode_Dori_Nikyo_omote_waza.mp4', 'Sode Dori <u>Nikyo omote</u> waza'],
	['04-Sode_Dori_nikyo_ura_waza.mp4', 'Sode Dori <u>nikyo ura</u> waza'],
	['05-Sode_Dori_Sankyo_omote_waza.mp4', 'Sode Dori <u>Sankyo omote</u> waza'],
	['06-Sode_Dori_Sankyo_ura_waza.mp4', 'Sode Dori <u>Sankyo ura</u> waza'],
	['07-Sode_Dori_Yonkyo_omote_waza.mp4', 'Sode Dori <u>Yonkyo omote</u> waza'],
	['08-Sode_Dori_Yonkyo_ura_waza.mp4', 'Sode Dori <u>Yonkyo ura</u> waza'],
	['09-Sode_Dori_Gokyo_omote_waza.mp4', 'Sode Dori <u>Gokyo omote</u> waza'],
	['10-Sode_Dori_Gokyo_ura_waza.mp4', 'Sode Dori <u>Gokyo ura</u> waza'],
	['11-Sode_Dori_Irimi_nage.mp4', 'Sode Dori <u>Irimi nage</u>'],
	['12-Sode_Dori_Irimi_nage_v2.mp4', 'Sode Dori <u>Irimi nage</u> v2'],
	['13-Sode_Dori_Kote_Gaeshi.mp4', 'Sode Dori <u>Kote Gaeshi</u>'],
	['14-Sode_Dori_Koshi_nage.mp4', 'Sode Dori <u>Koshi nage</u>'],
	['15-Sode_Dori_Kokyu_nage.mp4', 'Sode Dori <u>Kokyu nage</u>'],
	['16-Sode_Dori_Kenka_waza.mp4', 'Sode Dori Kenka waza'],
	['17-Sode_Dori_Kokyu_nage_v2.mp4', 'Sode Dori <u>Kokyu nage</u> v2'],
	['01-Sode_Guchi_Dori_Ikkyo_omote_waza.mp4', 'Sode Guchi Dori <u>Ikkyo omote</u> waza'],
	['02-Sode_Guchi_Dori_Ikkyo_ura_waza.mp4', 'Sode Guchi Dori <u>Ikkyo ura</u> waza'],
	['03-Sode_Guchi_Dori_Nikyo.mp4', 'Sode Guchi Dori <u>Nikyo</u>'],
	['04-Sode_Guchi_Dori_Sankyo_omote_waza.mp4', 'Sode Guchi Dori <u>Sankyo omote</u> waza'],
	['05-Sode_Guchi_Dori_Sankyo_ura_waza.mp4', 'Sode Guchi Dori <u>Sankyo ura</u> waza'],
	['06-Sode_Guchi_Dori_Yonkyo_omote_waza.mp4', 'Sode Guchi Dori <u>Yonkyo omote</u> waza'],
	['07-Sode_Guchi_Dori_Yonkyo_ura_waza.mp4', 'Sode Guchi Dori <u>Yonkyo ura</u> waza'],
	['08-Sode_Guchi_Dori_Shiho_nage_omote_waza.mp4', 'Sode Guchi Dori <u>Shiho nage omote</u> waza'],
	['09-Sode_Guchi_Dori_Shiho_nage_ura_waza.mp4', 'Sode Guchi Dori <u>Shiho nage ura</u> waza'],
	['10-Sode_Guchi_Dori_Irimi_nage.mp4', 'Sode Guchi Dori <u>Irimi nage</u>'],
	['11-Sode_Guchi_Dori_Kaiten_nage.mp4', 'Sode Guchi Dori <u>Kaiten nage</u>'],
	['12-Sode_Guchi_Dori______kaiten_nage.mp4', 'Sode Guchi Dori ____ <u>kaiten nage</u>'],
	['13-Sode_Guchi_Dori_Koshi_nage.mp4', 'Sode Guchi Dori <u>Koshi nage</u>'],
	['14-Sode_Guchi_Dori_Kokyu_nage_v1.mp4', 'Sode Guchi Dori <u>Kokyu nage</u> v1'],
	['15-Sode_Guchi_Dori_Kokyu_nage_v2.mp4', 'Sode Guchi Dori <u>Kokyu nage</u> v2'],
	['16-Sode_Guchi_Dori_Kokyu_nage_v3.mp4', 'Sode Guchi Dori <u>Kokyu nage</u> v3'],
	['17-Sode_Guchi_Dori_Kokyu_nage_v4.mp4', 'Sode Guchi Dori <u>Kokyu nage</u> v4'],
	['18-Sode_Guchi_Dori_Kenka_waza.mp4', 'Sode Guchi Dori Kenka waza'],
	['13-Taichi_Dori_01.mp4', 'Taichi Dori_01 voir profs'],
	['13-Taichi_Dori_02.mp4', 'Taichi Dori_02 voir profs'],
	['13-Taichi_Dori_03.mp4', 'Taichi Dori_03 voir profs'],
	['13-Taichi_Dori_04.mp4', 'Taichi Dori_04 voir profs'],
	['13-Taichi_Dori_05.mp4', 'Taichi Dori_05 voir profs'],
	['13-Taichi_Dori_06.mp4', 'Taichi Dori_06 voir profs'],
	['13-Taichi_Dori_07.mp4', 'Taichi Dori_07 voir profs'],
	['13-Taichi_Dori_08.mp4', 'Taichi Dori_08 voir profs'],
	['13-Taichi_Dori_09.mp4', 'Taichi Dori_09 voir profs'],
	['13-Taichi_Dori_10.mp4', 'Taichi Dori_10 voir profs'],
	['13-Taichi_Dori_11.mp4', 'Taichi Dori_11 voir profs'],
	['13-Taichi_Dori_12.mp4', 'Taichi Dori_12 voir profs'],
	['13-Taichi_Dori_13.mp4', 'Taichi Dori_13 voir profs'],
	['01-Yokomen_Uchi_Ikkyo_omote_waza.mp4', 'Yokomen Uchi <u>Ikkyo omote</u> waza'],
	['02-Yokomen_Uchi_Ikkyo_ura_waza.mp4', 'Yokomen Uchi <u>Ikkyo ura</u> waza'],
	['03-Yokomen_Uchi_Ikkyo_ura_waza_(ki_no_nagare).mp4', 'Yokomen Uchi <u>Ikkyo ura</u> waza (ki no nagare)'],
	['04-Yokomen_Uchi_Nikyo_omote_waza.mp4', 'Yokomen Uchi <u>Nikyo omote</u> waza'],
	['05-Yokomen_Uchi_Nikkyo_ura_waza.mp4', 'Yokomen Uchi <u>Nikkyo ura</u> waza'],
	['06-Yokomen_Uchi_Nikkyo_ura_waza_(Ki_no_nagare).mp4', 'Yokomen Uchi <u>Nikkyo ura</u> waza (Ki no nagare)'],
	['07-Yokomen_Uchi_Sankyo_omote_waza_(ikkyo_katate).mp4', 'Yokomen Uchi <u>Sankyo omote</u> waza (ikkyo katate)'],
	['08-Yokomen_Uchi_Sankyo_omote_waza_(ikkyo_katate)_v2.mp4', 'Yokomen Uchi <u>Sankyo omote</u> waza (ikkyo katate) v2'],
	['09-Yokomen_Uchi_Sankyo_omote_waza_(yon___).mp4', 'Yokomen Uchi <u>Sankyo omote</u> waza (yon __)'],
	['10-Yokomen_Uchi_Sankyo_omote_waza_(yon)_v2.mp4', 'Yokomen Uchi <u>Sankyo omote</u> waza (yon) v2'],
	['11-Yokomen_Uchi_Yonkyo_omote_waza.mp4', 'Yokomen Uchi <u>Yonkyo omote</u> waza'],
	['12-Yokomen_Uchi_Yonkyo_ura_waza.mp4', 'Yokomen Uchi <u>Yonkyo ura</u> waza'],
	['13-Yokomen_Uchi_Sankyo_ura_waza_(Ki_no_nagare).mp4', ' Yokomen Uchi <u>Sankyo ura</u> waza (Ki no nagare)'],
	['14-Yokomen_Uchi_Yonkyo_ura_waza_(Ki_no_nagare).mp4', 'Yokomen Uchi <u>Yonkyo ura</u> waza (Ki no nagare)'],
	['15-Yokomen_Uchi_Gokyo_omote_waza.mp4', 'Yokomen Uchi <u>Gokyo omote</u> waza'],
	['16-Yokomen_Uchi_Gokyo_ura_waza.mp4', 'Yokomen Uchi <u>Gokyo ura</u> waza'],
	['17-Yokomen_Uchi_Gokyo_ura_waza_(ki_no_nagare).mp4', 'Yokomen Uchi <u>Gokyo ura</u> waza (ki no nagare)'],
	['18-Yokomen_Uchi_Shiho_nage.mp4', 'Yokomen Uchi <u>Shiho nage</u>'],
	['19-Yokomen_Uchi_Shiho_nage_kenka.mp4', 'Yokomen Uchi <u>Shiho nage</u> kenka'],
	['20-Yokomen_Uchi_Irimi_nage.mp4', 'Yokomen Uchi <u>Irimi nage</u>'],
	['21-Yokomen_Uchi_Irimi_nage_v2.mp4', 'Yokomen Uchi <u>Irimi nage</u> v2'],
	['22-Yokomen_Uchi_Irimi_nage_(Ki_no_nagare).mp4', 'Yokomen Uchi <u>Irimi nage</u> Ki no nagare'],
	['23-Yokomen_Uchi_Irimi_nage_kenka_waza.mp4', 'Yokomen Uchi <u>Irimi nage</u> kenka waza'],
	['24-Yokomen_Uchi_Kote_Gaeshi.mp4', 'Yokomen Uchi <u>Kote Gaeshi</u>'],
	['25-Yokomen_Uchi_Kote_Gaeshi_kenka_waza.mp4', 'Yokomen Uchi <u>Kote Gaeshi</u> kenka waza'],
	['26-Yokomen_Uchi_Kaiten_nage.mp4', 'Yokomen Uchi <u>Kaiten nage</u>'],
	['27-Yokomen_Uchi_Koshi_nage.mp4', 'Yokomen Uchi <u>Koshi nage</u>'],
	['28-Yokomen_Uchi_Koshi_nage_v2.mp4', 'Yokomen Uchi <u>Koshi nage</u> v2'],
	['29-Yokomen_Uchi_Kokyu_nage.mp4', 'Yokomen Uchi <u>Kokyu nage</u>'],
	['30-Yokomen_Uchi_Kokyu_nage_v2.mp4', 'Yokomen Uchi <u>Kokyu nage</u> v2'],
	['31-Yokomen_Uchi_Kokyu_nage_v3.mp4', 'Yokomen Uchi <u>Kokyu nage</u> v3'],
	['32-Yokomen_Uchi_Kokyu_nage_v4.mp4', 'Yokomen Uchi <u>Kokyu nage</u> v4'],
	['33-Yokomen_Uchi_Oyo_waza.mp4', 'Yokomen Uchi <u>Oyo</u> waza'],
	['34-Yokomen_Uchi_Oyo_waza_v2.mp4', 'Yokomen Uchi <u>Oyo</u> waza v2'],
	['35-Yokomen_Uchi_Oyo_waza_v3.mp4', 'Yokomen Uchi <u>Oyo</u> waza v3'],
	['36-Yokomen_Uchi_(sans_nom).mp4', 'Yokomen Uchi (sans nom)'],
	['37-Yokomen_Uchi_(sans_nom)_v2.mp4', 'Yokomen Uchi (sans nom) v2'],
	['01-Muna_Dori_Ikkyo_omote_waza.mp4', 'Muna Dori <u>Ikkyo omote</u> waza'],
	['02-Muna_Dori_Ikkyo_ura_waza.mp4', 'Muna Dori <u>Ikkyo ura</u> waza'],
	['03-Muna_Dori_Nikyo.mp4', 'Muna Dori <u>Nikyo</u>'],
	['04-Muna_Dori_Nikyo_v2.mp4', 'Muna Dori <u>Nikyo</u> v2'],
	['05-Muna_Dori_Nikyo_v3.mp4', 'Muna Dori <u>Nikyo</u> v3'],
	['06-Muna_Dori_Nikyo_v4.mp4', 'Muna Dori <u>Nikyo</u> v4'],
	['07-Muna_Dori_Nikyo_v5.mp4', 'Muna Dori <u>Nikyo</u> v5'],
	['08-Muna_Dori_Nikyo_v6.mp4', 'Muna Dori <u>Nikyo</u> v6'],
	['09-Muna_Dori_Sankyo_omote_waza.mp4', 'Muna Dori <u>Sankyo omote</u> waza'],
	['10-Muna_Dori_Sankyo_ura_waza.mp4', 'Muna Dori <u>Sankyo ura</u> waza'],
	['11-Muna_Dori_Yonkyo_omote_waza.mp4', 'Muna Dori <u>Yonkyo omote</u> waza'],
	['12-Muna_Dori_Yonkyo_ura_waza.mp4', 'Muna Dori <u>Yonkyo ura</u> waza'],
	['13-Muna_Dori_Shiho_nage.mp4', 'Muna Dori <u>Shiho nage</u>'],
	['14-Muna_Dori_(no)_Kote_Gaeshi.mp4', 'Muna Dori (no) <u>Kote Gaeshi</u>'],
	['15-Muna_Dori_(no)_kote_Gaeshi_shomen_uchi.mp4', 'Muna Dori (no) <u>kote Gaeshi</u> shomen uchi'],
	['16-Muna_Dori_Juji_nage.mp4', 'Muna Dori <u>Juji nage</u>'],
	['17-Muna_Dori_Juji_nage_v2.mp4', 'Muna Dori <u>Juji nage</u> v2'],
	['18-Muna_Dori_Kokyu_Nage.mp4', 'Muna Dori <u>Kokyu Nage</u>'],
	['19-Muna_Dori_Kokyu_Nage_v2.mp4', 'Muna Dori <u>Kokyu Nage</u> v2'],
	['20-Muna_Dori_Kokyu_Nage_v3.mp4', 'Muna Dori <u>Kokyu Nage</u> v3'],
	['21-Muna_Dori_Kokyu_Nage_v4.mp4', 'Muna Dori <u>Kokyu Nage</u> v4'],
	['22-Muna_Dori_Kote_Gaeshi_(Ki_no_nagare).mp4', 'Muna Dori <u>Kote Gaeshi</u> (Ki no nagare)'],
	['23-Muna_Dori_Irimi_nage_(Ki_no_nagare).mp4', 'Muna Dori <u>Irimi nage</u> (Ki no nagare)'],
	['24-Muna_Dori_Irimi_nage_(Ki_no_nagare)_v2.mp4', 'Muna Dori <u>Irimi nage</u> (Ki no nagare) v2'],
	['25-Muna_Dori_Shiho_nage_(ki_no_nagare).mp4', 'Muna Dori <u>Shiho nage</u> ki no nagare'],
	['26-Muna_Dori_Koshi_nage_(ki_no_nagare).mp4', 'Muna Dori <u>Koshi nage</u> ki no nagare'],
	['27-Muna_Dori_Ikkyo_omote_(ki_no_nagare).mp4', 'Muna Dori <u>Ikkyo omote</u> ki no nagare'],
	['28-Muna_Dori_Ikkyo_ura_(ki_no_nagare).mp4', 'Muna Dori <u>Ikkyo ura</u> ki no nagare'],
	['29-Muna_Dori_Nikyo_omote_(ki_no_nagare).mp4', 'Muna Dori <u>Nikyo omote</u> ki no nagare'],
	['30-Muna_Dori_____Gat_(ki_no_nagare).mp4', 'Muna Dori ___ Gat ki no nagare'],
	['31-Muna_Dori_____Gat_(ki_no_nagare)_v2.mp4', 'Muna Dori ___ Gat ki no nagare v2'],
	['32-Muna_Dori_Koshi_nage_(ki_no_nagare).mp4', 'Muna Dori <u>Koshi nage</u> ki no nagare'],
	['33-Muna_Dori_Sankyo_(ki_no_nagare).mp4', 'Muna Dori <u>Sankyo</u> ki no nagare'],
	['34-Muna_Dori_Kenka_waza_(ki_no_nagare).mp4', 'Muna Dori Kenka waza ki no nagare'],
	['35-Muna_Dori_Kenka_waza_(ki_no_nagare)_v2.mp4', 'Muna Dori Kenka waza ki no nagare v2'],
	['36-Muna_Dori_Ki_no_nagare.mp4', 'Muna Dori Ki no nagare']
	['01-Jo_Suburi_Joku_Tsuki.mp4', 'Jo Suburi Joku Tsuki'],
	['02-Jo_Suburi_Kaiji_Tsuki.mp4', 'Jo Suburi Kaiji Tsuki'],
	['03-Jo_Suburi_Ushiro_Tsuki.mp4', 'Jo Suburi Ushiro Tsuki'],
	['04-Jo_Suburi_Tsuki_kenka_gedan_gaeshi.mp4', 'Jo Suburi Tsuki kenka <u>gedan gaeshi</u>'],
	['05-Jo_Suburi_Tsuki_kenka_Jodan_Gaeshi.mp4', 'Jo Suburi Tsuki kenka <u>Jodan Gaeshi</u>'],
	['06-Jo_Suburi_Shomen_uchi.mp4', 'Jo Suburi Shomen uchi'],
	['07-Jo_Suburi_Renzoku_uchi_komi.mp4', 'Jo Suburi Renzoku uchi komi'],
	['08-Jo_Suburi_Men_uchi_gedan_gaeshi.mp4', 'Jo Suburi Men uchi gedan gaeshi'],
	['09-Jo_Suburi_Men_uchi_ushiro_tsuki.mp4', 'Jo Suburi Men uchi ushiro tsuki'],
	['10-Jo_Suburi_Gyaku_Yokomen_ushiro_tsuki.mp4', 'Jo Suburi Gyaku Yokomen ushiro tsuki'],
	['11-Jo_Suburi_Katate_Gedan_Gaeshi.mp4', 'Jo Suburi Katate Gedan Gaeshi'],
	['12-Jo_Suburi_Katate_to_Mawashi.mp4', 'Jo Suburi Katate to Mawashi'],
	['13-Jo_Suburi_Katate_Hachiji_no_ji_gaeshi.mp4', 'Jo Suburi Katate Hachiji no ji gaeshi'],
	['14-Jo_Suburi_Hasso_Gaeshi_Uchi.mp4', 'Jo Suburi Hasso Gaeshi Uchi'],
	['15-Jo_Suburi_Hasso_Gaeshi_Tsuki.mp4', 'Jo Suburi Hasso Gaeshi Tsuki'],
	['16-Jo_Suburi_Hasso_Gaeshi_ushiro_Tsuki.mp4', 'Jo Suburi Hasso Gaeshi ushiro Tsuki'],
	['17-Jo_Suburi_Hasso_Gaeshi_ushiro_uchi.mp4', 'Jo Suburi Hasso Gaeshi ushiro uchi'],
	['18-Jo_Suburi_Hasso_Gaeshi_ushiro_barai.mp4', 'Jo Suburi Hasso Gaeshi ushiro barai'],
	['19-Jo_Suburi_Nagare_uchi.mp4', 'Jo Suburi Nagare uchi'],
	['20-Jo_Suburi_Migi_nagare_tsuki.mp4', 'Jo Suburi Migi nagare tsuki'],
	['21-Jo_Suburi_Joku_Tsuki_(vue_arrière).mp4', 'Jo Suburi Joku Tsuki (vue arrière)'],
	['22-Jo_Suburi_Kaeshi_Tsuki_(vue_arrière).mp4', 'Jo Suburi Kaeshi Tsuki (vue arrière)'],
	['23-Jo_Suburi_Ushiro_Tsuki_(vue_arrière).mp4', 'Jo Suburi Ushiro Tsuki (vue arrière)'],
	['24-Jo_Suburi_Tsuki_Gedan_Gaeshi_(vue_arrière).mp4', 'Jo Suburi Tsuki Gedan Gaeshi (vue arrière)'],
	['25-Jo_Suburi_Tsuki_jodan_gaeshi_uchi_(vue_arrière).mp4', 'Jo Suburi Tsuki jodan gaeshi uchi (vue arrière)'],
	['26-Jo_Suburi_Shomen_uchi_komi_(vue_arrière).mp4', 'Jo Suburi Shomen uchi komi (vue arrière)'],
	['27-Jo_Suburi_Renzoku_uchi_komi__(vue_arrière).mp4', 'Jo Suburi Renzoku uchi komi  (vue arrière)'],
	['28-Jo_Suburi_Men_uchi_Gedan_Gaeshi_(vue_arrière).mp4', 'Jo Suburi Men uchi Gedan Gaeshi (vue arrière)'],
	['29-Jo_Suburi_Men_uchi_ushiro_tsuki_(vue_arrière).mp4', 'Jo Suburi Men uchi ushiro tsuki (vue arrière)'],
	['30-Jo_Suburi_Gyaku_Yokomen_Ushiro_Tsuki_(vue_arrière).mp4', 'Jo Suburi Gyaku Yokomen Ushiro Tsuki (vue arrière)'],
	['31-_Jo_Suburi_Katate_Gedan_Gaeshi_(vue_arrière).mp4', ' Jo Suburi Katate Gedan Gaeshi (vue arrière)'],
	['32-Jo_Suburi_to_Mawashi_(vue_arrière).mp4', 'Jo Suburi to Mawashi (vue arrière)'],
	['33-Jo_Suburi_Hachi_no_ji_gaeshi_(vue_arrière).mp4', 'Jo Suburi Hachi no ji gaeshi (vue arrière)'],
	['34-Jo_Suburi_Hasso_Gaeshi_uchi_(vue_arrière).mp4', 'Jo Suburi Hasso Gaeshi uchi (vue arrière)'],
	['35-Jo_Suburi_Hasso_Gaeshi_Tsuki_(vue_arrière).mp4', 'Jo Suburi Hasso Gaeshi Tsuki (vue arrière)'],
	['36-Jo_Suburi_Hasso_Gaeshi_ushiro_Tsuki_(vue_arrière).mp4', 'Jo Suburi Hasso Gaeshi ushiro Tsuki (vue arrière)'],
	['37-Jo_Suburi_Hasso_Gaeshi_ushiro_Uchi_(vue_arrière).mp4', 'Jo Suburi Hasso Gaeshi ushiro Uchi (vue arrière)'],
	['38-Jo_Suburi_Hasso_Gaeshi_ushiro_barai_(vue_arrière).mp4', 'Jo Suburi Hasso Gaeshi ushiro barai (vue arrière)'],
	['39-Jo_Suburi_Nigari__Nagare_Gaeshi_uchi_(vue_arrière).mp4', 'Jo Suburi Nigari  Nagare Gaeshi uchi (vue arrière)'],
	['40-Jo_Suburi_Ni_ni_nagare_gaeshi_Tsuki_(vue_arrière).mp4', 'Jo Suburi Ni ni nagare gaeshi Tsuki (vue arrière)']



]