const nb = 8;
const questions = [
	[ '01-Ai_hanmi_katatedori_ikkyo_omote_waza.mp4', 'Ai hanmi katate dori <u>ikkyo omote</u> waza'],
	[ '02-Ai_hanmi_katatedori_ikkyo_ura_waza.mp4', 'Ai hanmi katate dori <u>ikkyo ura</u> waza'],
	[ '03-Ai_hanmi_katatedori_nikyo_omote_waza.mp4', 'Ai hanmi katate dori <u>nikyo omote</u> waza'],
	[ '04-Ai_hanmi_katatedori_nikyo_ura_waza.mp4', 'Ai hanmi katate dori <u>nikyo ura</u> waza'],
	[ '05-Ai_Hamni_Katate_Dori_Sankyo_omoto_waza.mp4', 'Ai hanmi katate dori <u>sankyo omote</u> waza'],
	[ '06-Ai_Hamni_Katate_Dori_sankyo_ura_waza.mp4', 'Ai hanmi katate dori <u>sankyo ura</u> waza'],
	[ '07-Ai_Hamni_Katate_Dori_Yonkyo_Omote_waza.mp4', 'Ai hanmi katate dori <u>yonkyo omote</u> waza'],
	[ '08-Ai_Hamni_Katate_Dori_yonkyo_ura_waza.mp4', 'Ai hanmi katate dori <u>yonkyo ura</u> waza'],
	[ '09-Ai_Hamni_Katate_Dori_Shiho_nage_omote.mp4', 'Ai hanmi katate dori <u>Shiho nage omote</u> waza'],
	[ '10-Ai_Hamni_Katate_Dori_Shiho_Nage_ura.mp4', 'Ai hanmi katate dori <u>Shiho nage ura</u> waza'],
	[ '11-Ai_Hamni_Katate_Dori_Irimi_Nage_v1.mp4', 'Ai hanmi katate dori <u>Irimi nage v1</u> waza'],
	[ '12-Ai_Hamni_Katate_Dori_Irimi_Nage_v2.mp4', 'Ai hanmi katate dori <u>Irimi nage v2</u> waza'],
	[ '13-Ai_Hamni_Katate_Dori_Irimi_Nage_v3.mp4', 'Ai hanmi katate dori <u>Irimi nage v3</u> waza'],
	[ '14-Ai_Hamni_Katate_Dori_KoteGaeshi_v1.mp4', 'Ai hanmi katate dori <u>Kote Gaeshi v1</u> waza'],
	[ '15-Ai_Hamni_Katate_Dori_KoteGaeshi_v2.mp4', 'Ai hanmi katate dori <u>Kote Gaeshi v2</u> waza'],
	[ '17-Ai_Hamni_Katate_Dori_Koshi_Nage.mp4', 'Ai hanmi katate dori <u>Irimi nage v2</u> waza'],
	[ '18-Ai_Hamni_Katate_Dori_-_Ushiro_nage.mp4', 'Ai hanmi katate dori <u>Ushiro nage</u> waza'],
	[ '19-Ai_Hamni_Katate_Dori_Ude_gatan.mp4', 'Ai hanmi katate dori <u>Ude Gatan</u> waza'],
	['01-Ryote_Dori_ikkyo_omote_waza.mp4', 'Ryote Dori ikkyo omote waza'],
	['02-Ryote_Dori_ikkyo_ura_waza.mp4', 'Ryote Dori ikkyo ura waza'],
	['03-Ryote_Dori_Nikyo_omote_waza.mp4', 'Ryote Dori Nikyo omote waza'],
	['04-Ryote_Dori_Nikyo_ura_waza.mp4', 'Ryote Dori Nikyo ura waza'],
	['05-Ryote_Dori_Sankyo_omote_waza.mp4', 'Ryote Dori Sankyo omote waza'],
	['06-Ryote_Dori_Sankyo_ura_waza.mp4', 'Ryote Dori Sankyo ura waza'],
	['07-Ryote_Dori_yonkyo_omote_waza.mp4', 'Ryote Dori yonkyo omote waza'],
	['08-Ryote_Dori_yonkyo_ura_waza.mp4', 'Ryote Dori yonkyo ura waza'],
	['09-Ryote_Dori_Gokyo_omote_waza.mp4', 'Ryote Dori Gokyo omote waza'],
	['10-Ryote_Dori_Gokyo_ura_waza.mp4', 'Ryote Dori Gokyo ura waza'],
	['11-Ryote_Dori_Shiho_nage_omote_waza.mp4', 'Ryote Dori Shiho nage omote waza'],
	['12-Ryote_Dori_Shiho_nage_ura_waza.mp4', 'Ryote Dori Shiho nage ura waza'],
	['13-Ryote_Dori_Shiho_nage_v3.mp4', 'Ryote Dori Shiho nage v3'],
	['14-Ryote_Dori_Irimi_nage_jodan.mp4', 'Ryote Dori Irimi nage jodan'],
	['15-Ryote_Dori_Irimi_nage_shiho_nage_jodan.mp4', 'Ryote Dori Irimi nage shiho nage jodan'],
	['16-Ryote_Dori_Irimi_nage_Gedan.mp4', 'Ryote Dori Irimi nage Gedan'],
	['17-Ryote_Dori_Shiho_nage_irimi_nage_gedan.mp4', 'Ryote Dori Shiho nage irimi nage gedan'],
	['18-Ryote_Dori_Irimi_nage_chudan.mp4', 'Ryote Dori Irimi nage chudan'],
	['19-Ryote_Dori_Kino_nage_irimi_nage_shodan.mp4', 'Ryote Dori Kino nage irimi nage shodan'],
	['20-Ryote_Dori_Kote_Gaeshi_v1.mp4', 'Ryote Dori Kote Gaeshi v1'],
	['21-Ryote_Dori_Kote_Gaeshi_v2.mp4', 'Ryote Dori Kote Gaeshi v2'],
	['22-Ryote_Dori_Kaiten_nage.mp4', 'Ryote Dori Kaiten nage'],
	['23-Ryote_Dori_Koshi_nage_v1.mp4', 'Ryote Dori Koshi nage v1'],
	['24-Ryote_Dori_Koshi_nage_v2.mp4', 'Ryote Dori Koshi nage v2'],
	['25-Ryote_Dori_Koshi_nage_v3.mp4', 'Ryote Dori Koshi nage v3'],
	['26-Ryote_Dori_Tenchi_nage.mp4', 'Ryote Dori Tenchi nage'],
	['27-Ryote_Dori_Shiho___tenchi_nage.mp4', 'Ryote Dori Shiho _ tenchi nage'],
	['28-Ryote_Dori_Kokyu_nage_v1.mp4', 'Ryote Dori Kokyu nage v1'],
	['29-Ryote_Dori_Kokyu_nage_v2.mp4', 'Ryote Dori Kokyu nage v2'],
	['30-Ryote_Dori_Kokyu_nage_v3.mp4', 'Ryote Dori Kokyu nage v3'],
	['31-Ryote_Dori_Ikkyo_waza.mp4', 'Ryote Dori Ikkyo waza'],
	['32-Ryote_Dori_Nikyo_waza.mp4', 'Ryote Dori Nikyo waza'],
	['Ryote_dori-33.mp4', 'Ryote dori 33'],
	['Ryote_dori-34.mp4', ' Ryote dori 34'],
	['Ryote_dori-35.mp4', 'Ryote dori 35'],
	['Ryote_dori-36.mp4', 'Ryote dori 36'],
['01-Tsuki_Ikkyo.mp4', 'Tsuki Ikkyo'],
['02-Tsuki_Nikyo.mp4', 'Tsuki Nikyo'],
['03-Tsuki_Shiho_nage.mp4', 'Tsuki Shiho nage'],
['04-Tsuki__Kote_gaeshi.mp4', 'Tsuki  Kote gaeshi'],
['05-Tsuki_Irimi_nage.mp4', 'Tsuki Irimi nage'],
['06-Tsuki_Sankyo.mp4', 'Tsuki Sankyo'],
['07-Tsuki_____v1.mp4', 'Tsuki ___ v1'],
['08-Tsuki_____v2.mp4', 'Tsuki ___ v2'],
['09-Tsuki_____v3.mp4', 'Tsuki ___ v3'],
['01-Ni_Nin_Dori_Kokyu_nage.mp4', 'Ni Nin Dori Kokyu nage'],
['02-Ni_Nin_Dori_Kokyu_nage_v2.mp4', 'Ni Nin Dori Kokyu nage v2'],
['03-Ni_Nin_Dori__Kokyu_nage_v3.mp4', 'Ni Nin Dori  Kokyu nage v3'],
['04-Ni_Nin_Dori_Ikkyo_waza.mp4', 'Ni Nin Dori Ikkyo waza'],
['05-Ni_Nin_Dori_Kokyu_nage_irimi_nage.mp4', 'Ni Nin Dori Kokyu nage irimi nage'],
['06-Ni_Nin_Dori_Kokyu_nage_v4.mp4', 'Ni Nin Dori Kokyu nage v4'],
['01-Ushiro_Ryote_Dori_Ikkyo_omote_waza.mp4', 'Ushiro Ryote Dori Ikkyo omote waza'],
['02-Ushiro_Ryote_Dori_Ikkyo_ura_waza.mp4', 'Ushiro Ryote Dori Ikkyo ura waza'],
['03-Ushiro_Ryote_Dori_Ikkyo_omote.mp4', 'Ushiro Ryote Dori Ikkyo omote'],
['04-Ushiro_Ryote_Dori_Ikkyo_ura.mp4', 'Ushiro Ryote Dori Ikkyo ura'],
['05-Ushiro_Ryote_Dori_Nikyo_omote_waza.mp4', 'Ushiro Ryote Dori Nikyo omote waza'],
['06-Ushiro_Ryote_Dori_Nikyo_Ura_waza.mp4', 'Ushiro Ryote Dori Nikyo Ura waza'],
['07-Ushiro_Ryote_Dori_Sankyo_omote_waza_.mp4', 'Ushiro Ryote Dori Sankyo omote waza '],
['08-Ushiro_Ryote_Dori_Sankyo_ura_waza.mp4', 'Ushiro Ryote Dori Sankyo ura waza'],
['09-Ushiro_Ryote_Dori_Yonkyo_omote_waza.mp4', 'Ushiro Ryote Dori Yonkyo omote waza'],
['10-Ushiro_Ryote_Dori__Yonkyo_ura_waza.mp4', 'Ushiro Ryote Dori  Yonkyo ura waza'],
['11-Ushiro_Ryote_Dori_Sankyo_Kenka_waza.mp4', 'Ushiro Ryote Dori Sankyo Kenka waza'],
['12-Ushiro_Ryote_Dori_Sankyo_v2.mp4', 'Ushiro Ryote Dori Sankyo v2'],
['13-Ushiro_Ryote_Dori_Irimi_nage.mp4', 'Ushiro Ryote Dori Irimi nage'],
['14-Ushiro_Ryote_Dori_Kote_Gaeshi.mp4', 'Ushiro Ryote Dori Kote Gaeshi'],
['15-Ushiro_Ryote_Dori_Kote_Gaeshi_v2.mp4', 'Ushiro Ryote Dori Kote Gaeshi v2'],
['16-Ushiro_Ryote_Dori_Koshinage.mp4', 'Ushiro Ryote Dori Koshinage'],
['17-Ushiro_Ryote_Dori_Kshinage_v2.mp4', 'Ushiro Ryote Dori Kshinage v2'],
['18-Ushiro_Ryote_Dori_Koshinage_v3.mp4', 'Ushiro Ryote Dori Koshinage v3'],
['19-Ushiro_Ryote_Dori_Juji_nage.mp4', 'Ushiro Ryote Dori Juji nage'],
['20-Ushiro_Ryote_Dori_Kokyu_ho.mp4', 'Ushiro Ryote Dori Kokyu ho'],
['21-Ushiro_Ryote_Dori_(sans_nom).mp4', 'Ushiro Ryote Dori (sans nom)'],
['22-Ushiro_Ryote_Dori_Ai_Hanmi.mp4', 'Ushiro Ryote Dori Ai Hanmi'],
['23-Ushiro_Ryote_Dori_Kokyu_nage.mp4', 'Ushiro Ryote Dori Kokyu nage'],
['24-Ushiro_Ryote_Dori_Kokyu_nage_v2.mp4', 'Ushiro Ryote Dori Kokyu nage v2'],
['25-Ushiro_Ryote_Dori_Kenka_waza.mp4', 'Ushiro Ryote Dori Kenka waza'],
['12_jo_dori-01.mp4', '12 jo dori 01 voir profs'],
['12_jo_dori-02.mp4', '12 jo dori 02 voir profs'],
['12_jo_dori-03.mp4', '12 jo dori 03 voir profs'],
['12_jo_dori-04.mp4', '12 jo dori 04 voir profs'],
['12_jo_dori-05.mp4', '12 jo dori 05 voir profs'],
['12_jo_dori-06.mp4', '12 jo dori 06 voir profs'],
['12_jo_dori-07.mp4', '12 jo dori 07 voir profs'],
['12_jo_dori-08.mp4', '12 jo dori 08 voir profs'],
['12_jo_dori-09.mp4', '12 jo dori 09 voir profs'],
['12_jo_dori-10.mp4', '12 jo dori 10 voir profs'],
['12_jo_dori-11.mp4', '12 jo dori 11 voir profs'],
['12_jo_dori-12.mp4', '12 jo dori 12 voir profs'],
['01-UW_Ushiro_Mune_katatedori_Kokyu_nage.mp4', 'UW Ushiro Mune katatedori Kokyu nage'],
['02-UW_Ushiro_Mune_katatedori_Ko_no_nagare_kokyu_nage.mp4', 'UW Ushiro Mune katatedori Ko no nagare kokyu nage'],
['03-UW_Ushiro_Mune_katatedori_koshinage.mp4', 'UW Ushiro Mune katatedori koshinage'],
['04-UW_Ushiro_Mune_katatedori_koshinage_v2.mp4', 'UW Ushiro Mune katatedori koshinage v2'],
['05-UW_Ki_no_nagare_Ushiro_Mune_katatedori_koshinage_v3.mp4', 'UW Ki no nagare Ushiro Mune katatedori koshinage v3'],
['06-UW_Ushiro_Mune_katatedori_Juji_nage.mp4', 'UW Ushiro Mune katatedori Juji nage'],
['07-UW_Ushiro_Mune_katatedori_Juji_nage_v2.mp4', 'UW Ushiro Mune katatedori Juji nage v2'],
['08-UW_Ushiro_Waza_katatedori_Juji_nage_v3.mp4', 'UW Ushiro Waza katatedori Juji nage v3'],
['09-UW_Ushiro_Mune_katate_dori_Kenka_waza.mp4', 'UW Ushiro Mune katate dori Kenka waza'],
['10-UW_Ushiro_Mune_katate_dori_Kenka_waza_v2.mp4', 'UW Ushiro Mune katate dori Kenka waza v2'],
['11-UW_Ushiro_Eri_Dori_Ikkyo_omote.mp4', 'UW Ushiro Eri Dori Ikkyo omote'],
['12-UW_Ushiro_Eri_Dori_Ikkyo_ura_waza.mp4', 'UW Ushiro Eri Dori Ikkyo ura waza'],
['13-UW_Ushiro_Eri_Dori_Nikyo.mp4', 'UW Ushiro Eri Dori Nikyo'],
['14-UW_Ushiro_Eri_Dori_Sankyo.mp4', 'UW Ushiro Eri Dori Sankyo'],
['15-UW_Ushiro_Eri_Dori_Yonkyo.mp4', 'UW Ushiro Eri Dori Yonkyo'],
['16-UW_Ushiro_Eri_Dori_Irimi_nage.mp4', 'UW Ushiro Eri Dori Irimi nage'],
['17-UW_Ushiro_Eri_Dori_Kokyu_nage.mp4', 'UW Ushiro Eri Dori Kokyu nage'],
['18-UW_Ushiro_Eri_Dori_Shiho_nage.mp4', 'UW Ushiro Eri Dori Shiho nage'],
['19-UW_Ushiro_Eri_Dori_Kote_Gaeshi.mp4', 'UW Ushiro Eri Dori Kote Gaeshi'],
['20-UW_Ushiro_Eri_Dori_Koshi_nage.mp4', 'UW Ushiro Eri Dori Koshi nage'],
['21-UW_Ushiro_Eri_Dori_Irimi_nage_v2.mp4', 'UW Ushiro Eri Dori Irimi nage v2'],
['22-UW_Ushiro_Eri_Dori_Kokyu_Nage_v2.mp4', 'UW Ushiro Eri Dori Kokyu Nage v2'],
['23-UW_Ushiro_Eri_Dori_Kenka_waza.mp4', 'UW Ushiro Eri Dori Kenka waza'],
['24-UW_Ushiro_Eri_Katate_dori_Irimi_nage.mp4', 'UW Ushiro Eri Katate dori Irimi nage'],
['25-UW_Ushiro_Ryo_kata_dori_Ikkyo_omote_waza.mp4', 'UW Ushiro Ryo kata dori Ikkyo omote waza'],
['26-UW_Ushiro_Ryo_kata_dori_Ikkyo_ura_waza.mp4', 'UW Ushiro Ryo kata dori Ikkyo ura waza'],
['27-UW_Ushiro_Ryo_kata_dori_Nikyo.mp4', 'UW Ushiro Ryo kata dori Nikyo'],
['28-UW_Ushiro_Ryo_kata_dori__Sankyo.mp4', 'UW Ushiro Ryo kata dori  Sankyo'],
['29-UW_Ushiro_Ryo_kata_dori_Yonkyo.mp4', 'UW Ushiro Ryo kata dori Yonkyo'],
['30-UW_Ushiro_Ryo_kata_dori_Kokyu_Nage.mp4', 'UW Ushiro Ryo kata dori Kokyu Nage'],
['31-UW_Ushiro_Ryo_kata_dori_Kokyu_Nage_v2.mp4', 'UW Ushiro Ryo kata dori Kokyu Nage v2'],
['32-UW_Ushiro_Ryo_kata_dori_Juji_nage.mp4', 'UW Ushiro Ryo kata dori Juji nage'],
['33-UW_Ushiro_Ryo_kata_dori_Kote_Gaeshi.mp4', 'UW Ushiro Ryo kata dori Kote Gaeshi'],
['34-UW_Ushiro_Ryo_kata_dori_Kenka_waza.mp4', 'UW Ushiro Ryo kata dori Kenka waza'],
['35-UW_Ushiro_Ryo_kata_dori_Kenka_waza_v2.mp4', 'UW Ushiro Ryo kata dori Kenka waza v2'],
['36-UW_Ushiro_Ryo_kata_dori_kenka_aiki_otoshi.mp4', 'UW Ushiro Ryo kata dori kenka aiki otoshi'],
['37-UW_Ushiro_Ryo_kata_dori____.mp4', 'UW Ushiro Ryo kata dori ___'],
['38-UW_Ushiro_Ryo_kata_dori_____v2.mp4', 'UW Ushiro Ryo kata dori ___ v2'],
['39-UW_Ushiro_Ryo_kata_dori______v3.mp4', 'UW Ushiro Ryo kata dori  ___ v3'],
['40-UW_Ushiro_Ryo_kata_dori_Osae____.mp4', 'UW Ushiro Ryo kata dori Osae ___'],
['41-UW_Ushiro_Dori_Kokyu_Nage.mp4', 'UW Ushiro Dori Kokyu Nage'],
['42-UW_Ushiro_Dori_Sankyo.mp4', 'UW Ushiro Dori Sankyo'],
['43-UW_Ushiro_Dori_Kenka_waza.mp4', 'UW Ushiro Dori Kenka waza'],
['44-UW_Ushiro_Dori_Kenka_waza_v2.mp4', 'UW Ushiro Dori Kenka waza v2']

]
