const nb = 5;
const questions = [
	[ 'Hanmi_hantachi_waza.png', 'Hanmi hantachi waza'],
	[ 'Suwari_waza.png', 'Suwari waza'],
	[ 'Tachi_waza.png', 'Tachi waza'],
	[ '01-Ai_hanmi_katatedori_ikkyo_omote_waza.mp4', 'Ai hanmi katate dori'],
	[ '02-Ai_hanmi_katatedori_ikkyo_ura_waza.mp4', 'Ai hanmi katate dori'],
	[ '03-Ai_hanmi_katatedori_nikyo_omote_waza.mp4', 'Ai hanmi katate dori'],
	[ '04-Ai_hanmi_katatedori_nikyo_ura_waza.mp4', 'Ai hanmi katate dori'],
	[ '05-Ai_Hamni_Katate_Dori_Sankyo_omoto_waza.mp4', 'Ai hanmi katate dori'],
	[ '06-Ai_Hamni_Katate_Dori_sankyo_ura_waza.mp4', 'Ai hanmi katate dori'],
	['02-Ryote_Dori_ikkyo_ura_waza.mp4', 'Ryote Dori'],
	['03-Ryote_Dori_Nikyo_omote_waza.mp4', 'Ryote Dori'],
	['04-Ryote_Dori_Nikyo_ura_waza.mp4', 'Ryote Dori'],
	['05-Ryote_Dori_Sankyo_omote_waza.mp4', 'Ryote Dori'],
	['06-Ryote_Dori_Sankyo_ura_waza.mp4', 'Ryote Dori'],
['01-Katate_dori_ikkyo_omote_waza.mp4', 'Katate dori'],
['02-Katate_dori_ikkyo_ura_waza.mp4', 'Katate dori'],
['03-Katate_Dori_Nikyo_omote_waza_.mp4', 'Katate Dori'],
['04-Katate_Dori_Nikyo_ura_waza.mp4', 'Katate Dori'],
['05-Katate_Dori_Sankyo_omote_waza_.mp4', 'Katate Dori'],
['06-Katate_Dori_Sankyo_ura_waza.mp4', 'Katate Dori'],
	['01-Shomen_Uchi_Ikkyo_omote_waza.mp4', 'Shomen Uchi'],
['02-Shomen_Uchi_Ikkyo_ura_waza.mp4', 'Shomen Uchi'],
['03-Shomen_Uchi_Nikyo_omote_waza.mp4', 'Shomen Uchi'],
['04-Shomen_Uchi_Nikyo_ura_waza.mp4', 'Shomen Uchi'],
['05-Shomen_Uchi_Sankyo_omote_waza_v1.mp4', 'Shomen Uchi'],
	['01-Tsuki_Ikkyo.mp4', 'Tsuki'],
['02-Tsuki_Nikyo.mp4', 'Tsuki'],
['03-Tsuki_Shiho_nage.mp4', 'Tsuki'],
	['01-Ushiro_Ryote_Dori_Ikkyo_omote_waza.mp4', 'Ushiro Ryote Dori'],
['02-Ushiro_Ryote_Dori_Ikkyo_ura_waza.mp4', 'Ushiro Ryote Dori'],
['03-Ushiro_Ryote_Dori_Ikkyo_omote.mp4', 'Ushiro Ryote Dori'],
['04-Ushiro_Ryote_Dori_Ikkyo_ura.mp4', 'Ushiro Ryote Dori'],
['03-UW_Ushiro_Mune_katatedori_koshinage.mp4', 'Ushiro Mune katatedori'],
['06-UW_Ushiro_Mune_katatedori_Juji_nage.mp4', 'Ushiro Mune katatedori'],
['11-UW_Ushiro_Eri_Dori_Ikkyo_omote.mp4', 'Ushiro Eri Dori'],
['12-UW_Ushiro_Eri_Dori_Ikkyo_ura_waza.mp4', 'Ushiro Eri Dori'],
['13-UW_Ushiro_Eri_Dori_Nikyo.mp4', 'Ushiro Eri Dori'],
['07-Morote_Dori_Ikkyo_omote_waza.mp4', 'Morote Dori'],
['08-Morote_Dori_Ikkyo_ura_waza.mp4', 'Morote Dori'],
['11-Morote_Dori_Nikyo.mp4', 'Morote Dori'],
['01-Sode_Dori_Ikkyo_omote_waza.mp4', 'Sode Dori'],
['02-Sode_Dori_Ikkyo_ura_waza.mp4', 'Sode Dori'],
['03-Sode_Dori_Nikyo_omote_waza.mp4', 'Sode Dori'],
['01-Sode_Guchi_Dori_Ikkyo_omote_waza.mp4', 'Sode Guchi Dori'],
['02-Sode_Guchi_Dori_Ikkyo_ura_waza.mp4', 'Sode Guchi Dori'],
['03-Sode_Guchi_Dori_Nikyo.mp4', 'Sode Guchi Dori'],
['01-Yokomen_Uchi_Ikkyo_omote_waza.mp4', 'Yokomen Uchi'],
['02-Yokomen_Uchi_Ikkyo_ura_waza.mp4', 'Yokomen Uchi'],
['03-Yokomen_Uchi_Ikkyo_ura_waza_(ki_no_nagare).mp4', 'Yokomen Uchi'],
['04-Yokomen_Uchi_Nikyo_omote_waza.mp4', 'Yokomen Uch'],
['05-Yokomen_Uchi_Nikkyo_ura_waza.mp4', 'Yokomen Uchi'],
['01-Muna_Dori_Ikkyo_omote_waza.mp4', 'Muna Dori Ikkyo omote waza'],
['02-Muna_Dori_Ikkyo_ura_waza.mp4', 'Muna Dori Ikkyo ura waza'],
['03-Muna_Dori_Nikyo.mp4', 'Muna Dori Nikyo'],
['01-Ni_Nin_Dori_Kokyu_nage.mp4', 'Ni Nin Dori']
]